name: Daily Update Status

on:
  schedule:
    - cron: '0 0 * * *'  # ทุกวันตอน 00:00 UTC
  workflow_dispatch:

jobs:
  update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout data-files branch
        uses: actions/checkout@v3
        with:
          ref: data-files

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Run update_status_daily.py
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: python backend/update_status_daily.py
