name: Daily Notify Ending Exhibitions

on:
  schedule:
    - cron: '0 3 * * *' # 03:00 UTC = 10:00 ไทย
  workflow_dispatch:

jobs:
  notify-ending:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout backend branch
      uses: actions/checkout@v3
      with:
        ref: backend

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run notifyEndingExhibitions
      run: node cron/notifyEndingExhibitions.js
