name: Notify Ending Exhibitions

on:
  schedule:
    - cron: '0 3 * * *'  # ทุกวันเวลา 10:00 น. (ไทย)
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout backend branch
        uses: actions/checkout@v3
        with:
          ref: backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run notifyEndingExhibitions.js
        env:
          EMAIL_USERNAME: inspira.project2025@gmail.com
          EMAIL_PASSWORD: nwxrzwzhyvnvannc
          BASE_URL: http://localhost:5000
        run: node cron/notifyEndingExhibitions.js
